export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST'
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS'
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST'
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS'
export const PRODUCT_DETAIL_FAIL = 'PRODUCT_DETAIL_FAIL'

export const REVIEW_REQUEST = 'REVIEW_REQUEST'
export const REVIEW_SUCCESS = 'REVIEW_SUCCESS'
export const REVIEW_FAIL = 'REVIEW_FAIL'
export const REVIEW_RESET = 'REVIEW_RESET'

export const PRODUCT_REVIEWS_REQUEST = 'PRODUCT_REVIEWS_REQUEST'
export const PRODUCT_REVIEWS_SUCCESS = 'PRODUCT_REVIEWS_SUCCESS'
export const PRODUCT_REVIEWS_FAIL = 'PRODUCT_REVIEWS_FAIL'

export const ADMIN_PRODUCTS_REQUEST = 'ADMIN_PRODUCTS_REQUEST'
export const ADMIN_PRODUCTS_SUCCESS = 'ADMIN_PRODUCTS_SUCCESS'
export const ADMIN_PRODUCTS_FAIL = 'ADMIN_PRODUCTS_FAIL'

export const NEW_PRODUCT_REQUEST = 'NEW_PRODUCT_REQUEST'
export const NEW_PRODUCT_SUCCESS = 'NEW_PRODUCT_SUCCESS'
export const NEW_PRODUCT_FAIL = 'NEW_PRODUCT_FAIL'
export const NEW_PRODUCT_RESET = 'NEW_PRODUCT_RESET'

export const ADMIN_ORDERS_REQUEST = 'ADMIN_ORDERS_REQUEST'
export const ADMIN_ORDERS_SUCCESS = 'ADMIN_ORDERS_SUCCESS'
export const ADMIN_ORDERS_FAIL = 'ADMIN_ORDERS_FAIL'
