export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST'
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS'
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST'
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS'
export const PRODUCT_DETAIL_FAIL = 'PRODUCT_DETAIL_FAIL'

export const REVIEW_REQUEST = 'REVIEW_REQUEST'
export const REVIEW_SUCCESS = 'REVIEW_SUCCESS'
export const REVIEW_FAIL = 'REVIEW_FAIL'
export const REVIEW_RESET = 'REVIEW_RESET'
